---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: monitoring
  name: targets
  labels:
    prometheus: main
spec:
  groups:
    - name: targets
      rules:
        - alert: PrometheusTargetMissing
          expr: up == 0
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: Prometheus target missing (instance {{ $labels.instance }})
            description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
        - alert: EndPointDown
          expr: probe_success == 0
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: Endpoint is down (instance {{ $labels.instance }})
            description: "Endpoint {{ $labels.instance }} down"
        - alert: PodRestart
          expr: rate(k8s_container_restarts[1h]) * 3600 > 1
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: Endpoint is down (instance {{ $labels.instance }})
            description: "Endpoint {{ $labels.instance }} down"