---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: ogtl-com-web
  namespace: monitoring
  labels:
    prometheus: main
spec:
  jobName: ogtl-web
  interval: 15s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring:9115
  targets:
    staticConfig:
      static:
        - https://vreg.gov.ng
        - https://www.vreg.gov.ng
        - https://vreg.gov.ng/api
        - https://idec.gov.ng
        - https://api.idec.gov.ng
        