---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: ogtl-com-web
  namespace: monitoring
  labels:
    prometheus: main
spec:
  jobName: ogtl-web
  interval: 15s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring:9115
  targets:
    staticConfig:
      static:
        - http://vregfrontend-deployment-chart.vreg.svc.cluster.local
        - http://vreg-deployment-chart.vreg.svc.cluster.local
        - http://idec-deployment-chart.vreg.svc.cluster.local
        - http://idec-frontend-deployment-chart.vreg.svc.cluster.local
        