---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: aputra/myapp-lesson154:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: http-metrics # you have to name your ports because this will be used by pod/service monitors
              containerPort: 8081
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 200m