---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp
  namespace: staging
  labels:
    prometheus: main # must match the label used in the prometheus object
spec:
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      app: myapp-monitoring # Important Note: this should select the label on the prom-service
  endpoints:
    - port: http-metrics # Here, we are using the service named port not the deployment named port
      path: /metrics