apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: monitoring
  labels:
    operated-prometheus: 'true'
spec:
  ports:
    - name: web-access
      protocol: TCP
      port: 80
      targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
  type: NodePort