---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
  # annotations:
  #   eks.amazonaws.com/role-arn: "arn:aws:iam::<acc-id>:role/prometheus"
  # bind an IAM role with this service account