---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: alertmanager-main
type: Opaque
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 10m
    route:
      group_by:
        - alertname
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: slack-notifications
      routes:
      - receiver: slack-notifications
        match:
          severity: critical
    receivers:
    - name: slack-notifications
      slack_configs:
      - channel: "#application-uptime"
        send_resolved: true
        api_url: ""
        title: |-
          '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
        text: |-
          {{ range .Alerts }}"
            "*Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`"
            "*Description:* {{ .Annotations.description }}"
            "*Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:> *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>"
            "*Details:*"
            "{{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`"
            "{{ end }}"
          "{{ end }}"
    templates:
    - '/etc/alertmanager/config/*.tmpl'